#!/bin/bash


echo "$(tput setaf 3) ____ __________ ____    _  _____ "
echo "/ ___|__  / ____/ ___|  / \|_   _|"
echo "\___ \ / /|  _| \___ \ / _ \ | |  "
echo " ___) / /_| |___ ___) / ___ \| |  "
echo "|____/____|_____|____/_/   \_\_|  "
echo "==================================="
echo "==     Github szinkronizálás     =="
echo "===================================$(tput sgr 0)"
echo ""

#Frissítsük a meglévő adatokat, kerssünk változást!

#cd /home/pi/Desktop/Silurus_uj
git init
#git pull origin master

#Változások feltöltése

git add .
git commit -m "PI feltoltes $(date '+%d/%m/%Y-%H:%M:%S')";

echo "$(tput setaf 3)"
echo "Falhasználó: SZESAT"
echo "Jelszó: DTetejénVan201"
echo "$(tput sgr 0)"

git push origin master

